### ISSUE TITLE
新版pmm安装

### ISSUE THREAD

**Issue by liuyangc3** [nxintech/Charlie#15]
1 ansible playbook
```yaml
---
- hosts: pmm-server01.produce.zs
  become: yes
  gather_facts: yes

  tasks:
    - name: Packages                   | Add Percona repository
      when: ansible_os_family == 'RedHat'
      yum:
        name: https://www.percona.com/redir/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm
        state: installed

    - name: Packages                   | Update OS
      when: ansible_os_family == 'RedHat'
      yum:
        name: '*'
        state: latest
        exclude: 'ansible'
        disablerepo: percona-release-x86_64

    - name: Packages                   | Install OS tools
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed
      with_items:
        - screen
        - yum-utils
        - yum-cron
        - logrotate

    - name: PMM                        | Add PMM Server YUM repository
      when: ansible_os_family == 'RedHat'
      yum_repository:
        name: pmm
        description: PMM Server YUM repository - x86_64
        baseurl: https://repo.percona.com/pmm/7/RPMS/x86_64/
        gpgcheck: yes
        enabled: no
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Percona

    - name: PMM                        | Add PMM Server YUM repository
      when: ansible_os_family == 'RedHat'
      yum_repository:
        name: pmm-laboratory
        description: PMM Server YUM repository - x86_64
        baseurl: https://repo.percona.com/laboratory/7/RPMS/x86_64/
        gpgcheck: yes
        enabled: no
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Percona

    - name: PMM                        | Install RPMs
      when: ansible_os_family == 'RedHat'
      yum: name={{ item }} state=installed enablerepo=pmm-laboratory
      with_items:
        - percona-consul
        - percona-orchestrator
        - percona-qan-api
        - percona-qan-app
        - percona-toolkit
        - pmm-manage
        - pmm-managed
        - pmm-update
```

**Comment by liuyangc3** [comment]
2 修改 qan-api 配置 /usr/share/percona-qan-api/src/github.com/percona/qan-api/conf/prod.conf 
```patch
- api.base.path = 
- mysql.dsn = percona:percona@tcp(localhost:3306)/pmm?parseTime=true&interpolateParams=true&time_zone="%2B00%3A00"&loc=UTC
+ api.base.path = /qan-api
+ mysql.dsn = percona:percona@tcp(localhost:3306)/pmm?parseTime=true&interpolateParams=true&time_zone="%2B00%3A80"&loc=Local

```

**Comment by liuyangc3** [comment]
手动启动报错
```
PERCONA_DATASTORE_BASEDIR=/usr/share/percona-qan-api/src/github.com/percona/qan-api
PERCONA_DATASTORE_CONF=/usr/share/percona-qan-api/src/github.com/percona/qan-api/conf/prod.conf

/usr/share/percona-qan-api/bin/percona-qan-api -importPath github.com/percona/qan-api -srcPath /usr/share/percona-qan-api/src -runMode prod

ERROR: logging before flag.Parse: I1219 13:47:47.278580  124889 logutil.go:31] log: Config dev.conf not found in paths: 
panic: Config dev.conf not found in paths: 

goroutine 1 [running]:
log.Panic(0xc420183ea8, 0x1, 0x1)
        /usr/local/go/src/log/log.go:326 +0xc0
github.com/percona/qan-api/config.init.0()
        /root/build/src/github.com/percona/qan-api/config/config.go:50 +0xd2
...
```
出现了  `panic: Config dev.conf not found in paths: `

源码 qan-api/config.go
```go
// line 50
confPaths := getConfPaths()
	for _, confPath := range confPaths {
		log.Printf("Loading %s/%s", confPath, configFile)
		conf, err := config.ReadDefault(path.Join(confPath, configFile))
		if err == nil {
			setRootDir(confPath)
			return conf, nil
		}
	}

err = errors.New(fmt.Sprintf("Config %s not found in paths: %s", configFile, strings.Join(confPaths, ", ")))
```
应该是 confPaths  没有正确加载

**Comment by liuyangc3** [comment]
qan-api 采用 rpm 方式， 安装
rpm -ivh https://repo.percona.com/pmm/7/RPMS/x86_64/percona-qan-api-1.5.3-2.1712052126.db3d0e5.el7.x86_64.rpm


bashrc 中加入
```
alias lt='tail -f /data0/logs/percona-qan-api.log'
alias st='/usr/sbin/percona-qan-api -importPath github.com/percona/qan-api -srcPath /usr/share/percona-qan-api/src -runMode prod >> /data0/logs/percona-qan-api.log 2>&1 &'

# set env that qan-api require
export PERCONA_DATASTORE_BASEDIR=/usr/share/percona-qan-api/src/github.com/percona/qan-api
export PERCONA_DATASTORE_CONF=/usr/share/percona-qan-api/src/github.com/percona/qan-api/conf/prod.conf
```

**Comment by liuyangc3** [comment]
修改 consul启动脚本  /usr/lib/systemd/system/consul.service

```patch
- ExecStart=/usr/sbin/consul agent $OPTIONS -config-dir /etc/consul.d -data-dir $DATA_DIR
+ ExecStart=/usr/sbin/consul agent -ui -server -bootstrap -client=0.0.0.0 -config-dir /etc/consul.d -data-dir $DATA_DIR 
```
启动 consul
```
systemctl daemon-reload
service consul start
```

**Comment by liuyangc3** [comment]
修改 prometheus  nginx 配置
```
    rewrite             ^/prometheus$ /prometheus/;
    location /prometheus {
        rewrite    ^/prometheus/(.*) /$1 break;
        proxy_pass http://prometheus:9090;
    }
```

**Comment by liuyangc3** [comment]
agent 编译
```
cd $GOPATH
git clone https://github.com/percona/qan-agent.git
cd qan-agent && git checkout tags/v1.5.3 && cd build
DEV=no ./build
```
编译后的文件已经上传到本项目的 release

解压build下tar.gz 到 /usr/local/percona/qan-agent，并安装
```
cd /usr/local/percona/qan-agent
# install
bin/percona-qan-agent-installer -server-user admin -server-pass <passwprld> http://admin:<passwprld> @pmm.nxin.com/qan-api

API host: http://admin:<passwprld> @pmm.nxin.com/qan-api
Created OS: name=qlw-mysql-5.7-master.produce.yz uuid=e8a71f13db5b4a4b6cc926d4dbba9f3f
Created agent instance: name=qlw-mysql-5.7-master.produce.yz uuid=1128b2805f914bb26c688c7a62e005a8
```

**Comment by liuyangc3** [comment]
批量重新安装 agent
```
---
- hosts: mysqlserver
  gather_facts: false
  vars:
    location: /usr/local/percona/qan-agent
    pkg: percona-qan-agent-v1.5.3-x86_64.tar.gz
    name: percona-qan-agent-1.0.5-20171225.a9a8d40-x86_64
  tasks:

  - name: remove old qan-agent
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
        - { path: "{{ location }}/bin" }
        - { path: "{{ location }}/config" }
        - { path: "{{ location }}/data" }
        - { path: "{{ location }}/instance" }
        - { path: "{{ location }}/trash/data" }

  - name: copy {{pkg}}
    copy: src=/root/{{pkg}} dest=/tmp/{{pkg}} mode=0744
  - name: unzip {{pkg}}| install
    shell: "{{ item.cmd }}"
    with_items:
      - { cmd: "tar zxf /tmp/{{pkg}} -C /tmp" }
      - { cmd: "mv /tmp/{{name}}/bin {{location}}" }
      - { cmd: "{{location}}/bin/percona-qan-agent-installer -server-user admin -server-pass admin http://admin:admin@pmm.nxin.com/qan-api" }

  - name: delete {{pkg}}
    file:
      path: "{{ item.path }}"
      state: absent
    with_items:
      - { path: "/tmp/{{pkg}}" }
      - { path: "/tmp/{{name}}" }
```
